const SavedData =[
    {
        "id": "1",
        "savedByLoop": "true",
        "expired_in": "2",
        "logo":"https://gwg",
        "job_title":"UI/UX Designer",
        "company":"Ajmera Infotech Inc.",
        "resume":"75",
        "error":"0",
    },
    {
        "id": "2",
        "savedByLoop": "false",
        "expired_in": "2",
        "logo":"https://gwg",
        "job_title":"UI/UX Designer",
        "company":"Ajmera Infotech Inc.",
        "resume":"75",
        "error":"0",
    },
    {
        "id": "3",
        "savedByLoop": "false",
        "expired_in": "2",
        "logo":"https://gwg",
        "job_title":"UI/UX Designer",
        "company":"Ajmera Infotech Inc.",
        "resume":"75",
        "error":"25",
    },
    {
        "id": "4",
        "savedByLoop": "false",
        "expired_in": "2",
        "logo":"https://gwg",
        "job_title":"UI/UX Designer",
        "company":"Ajmera Infotech Inc.",
        "resume":"75",
        "error":"0",
    },
    {
        "id": "5",
        "savedByLoop": "false",
        "expired_in": "2",
        "logo":"https://gwg",
        "job_title":"UI/UX Designer",
        "company":"Ajmera Infotech Inc.",
        "resume":"75",
        "error":"0",
    },
]

export default SavedData;